package com.cindy.eros.admin.model;

import java.util.Date;

public class Secret {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secret.id
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secret.user_id
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secret.content
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secret.img
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    private Date img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secret.create_time
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secret.update_time
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secret.id
     *
     * @return the value of secret.id
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secret.id
     *
     * @param id the value for secret.id
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secret.user_id
     *
     * @return the value of secret.user_id
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secret.user_id
     *
     * @param userId the value for secret.user_id
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secret.content
     *
     * @return the value of secret.content
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secret.content
     *
     * @param content the value for secret.content
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secret.img
     *
     * @return the value of secret.img
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    public Date getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secret.img
     *
     * @param img the value for secret.img
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    public void setImg(Date img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secret.create_time
     *
     * @return the value of secret.create_time
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secret.create_time
     *
     * @param createTime the value for secret.create_time
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secret.update_time
     *
     * @return the value of secret.update_time
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secret.update_time
     *
     * @param updateTime the value for secret.update_time
     *
     * @mbggenerated Tue Aug 07 20:33:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}